{{- if .Values.kubeaudio.enable }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeaudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeaudio
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubeaudio
    spec:
      containers:
        - name: kubeaudio
          image: djsasha777/kubeaudio:{{ .Values.kubeaudio.image }}
          securityContext:
            privileged: true
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
          env:
            - name: AIRPLAYNAME
              value: {{ .Values.kubeaudio.devicename }}
      initContainers:
        - name: init-alsa
          image: busybox:1.28
          command: /usr/bin/nsenter
          args:
          - /bin/bash 
          - 'apt' 
          - 'install'
          - 'alsa-tools'
      volumeMounts:
        mountPath: /dev/snd
        name: dev-snd
      volumes:
      - name: dev-snd
        hostPath:
          path: /dev/snd
      nodeName: {{ .Values.kubeaudio.nodename }}

---
apiVersion: v1
kind: Service
metadata:
  name: kubeaudio
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
  selector:
    app: kubeaudio
  type: NodePort
{{- end }}