name: kubeaudio
on:
  push:
    tags:
      - "*.*.*"
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker meta here
        id: metahere
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/virtualhere
          tags: |
            type=schedule
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
      - name: Build virtualhere
        uses: docker/build-push-action@v3
        with:
          context: .
          file: virtualhere.Dockerfile
          push: true
          tags: ${{ steps.metahere.outputs.tags }}